steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'europe-west3-docker.pkg.dev/$PROJECT_ID/$REPO_NAME', '.']
- name: 'gcr.io/cloudshell-images/custom-image-validation'
  args: ['image_test.py', '--image', 'europe-west3-docker.pkg.dev/$PROJECT_ID/$REPO_NAME']
images: ['europe-west3-docker.pkg.dev/$PROJECT_ID/$REPO_NAME']
timeout: '1200s'
